# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/shakira/setup-makefiles.sh
PRODUCT_COPY_FILES += \
    vendor/semc/shakira/proprietary/lib/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/semc/shakira/proprietary/bin/akmd2:system/bin/akmd2 \
    vendor/semc/shakira/proprietary/bin/mm-venc-omx-test:system/bin/mm-venc-omx-test \
    vendor/semc/shakira/proprietary/etc/01_qcomm_omx.cfg:system/etc/01_qcomm_omx.cfg \
    vendor/semc/shakira/proprietary/bin/nvimport:system/bin/nvimport \
    vendor/semc/shakira/proprietary/lib/libZiEngine.so:system/lib/libZiEngine.so \
    vendor/semc/shakira/proprietary/usr/keylayout/shakira_keypad.kl:system/usr/keylayout/shakira_keypad.kl \
    vendor/semc/shakira/proprietary/usr/keychars/shakira_keypad.kcm.bin:system/usr/keychars/shakira_keypad.kcm.bin \
    vendor/semc/shakira/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/semc/shakira/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/semc/shakira/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/semc/shakira/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/semc/shakira/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/semc/shakira/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/semc/shakira/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/semc/shakira/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/semc/shakira/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/semc/shakira/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/semc/shakira/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/semc/shakira/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/semc/shakira/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/semc/shakira/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/semc/shakira/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/semc/shakira/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/semc/shakira/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/semc/shakira/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/semc/shakira/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/semc/shakira/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/semc/shakira/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/semc/shakira/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/semc/shakira/proprietary/etc/firmware/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/shakira/proprietary/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/shakira/proprietary/etc/firmware/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/shakira/proprietary/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/shakira/proprietary/etc/firmware/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/shakira/proprietary/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/shakira/proprietary/etc/firmware/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts \
    vendor/semc/shakira/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/semc/shakira/proprietary/bin/semc_chargalg:system/bin/semc_chargalg \
    vendor/semc/shakira/proprietary/bin/updatemiscta:system/bin/updatemiscta \
    vendor/semc/shakira/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim1.rle:system/etc/semc/chargemon/anim1.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim2.rle:system/etc/semc/chargemon/anim2.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim3.rle:system/etc/semc/chargemon/anim3.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim4.rle:system/etc/semc/chargemon/anim4.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim5.rle:system/etc/semc/chargemon/anim5.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim6.rle:system/etc/semc/chargemon/anim6.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim7.rle:system/etc/semc/chargemon/anim7.rle \
    vendor/semc/shakira/proprietary/etc/semc/chargemon/anim8.rle:system/etc/semc/chargemon/anim8.rle \
    vendor/semc/shakira/proprietary/etc/permissions/com.sonyericsson.smfmf.xml:system/etc/permissions/com.sonyericsson.smfmf.xml \
    vendor/semc/shakira/proprietary/etc/permissions/com.sonyericsson.suquashi.xml:system/etc/permissions/com.sonyericsson.suquashi.xml \
    vendor/semc/shakira/proprietary/lib/libfm_stack.so:system/lib/libfm_stack.so \
    vendor/semc/shakira/proprietary/etc/permissions/com.dsi.ant.antradio_library.xml:system/etc/permissions/com.dsi.ant.antradio_library.xml \
    vendor/semc/shakira/proprietary/framework/com.dsi.ant.antradio_library.jar:system/framework/com.dsi.ant.antradio_library.jar \
    vendor/semc/shakira/proprietary/lib/libanthal.so:system/lib/libanthal.so \
    vendor/semc/shakira/proprietary/etc/sensors.conf:system/etc/sensors.conf \
    vendor/semc/shakira/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/semc/shakira/proprietary/lib/hw/hal_seport.default.so:system/lib/hw/hal_seport.default.so \
    vendor/semc/shakira/proprietary/lib/libsystemconnector/libuinputdevicejni.so:system/lib/libsystemconnector/libuinputdevicejni.so \
    vendor/semc/shakira/proprietary/lib/libsystemconnector_hal_jni.so:system/lib/libsystemconnector_hal_jni.so \
    vendor/semc/shakira/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/semc/shakira/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/semc/shakira/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/semc/shakira/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/semc/shakira/proprietary/lib/libfacedetect.so:system/lib/libfacedetect.so \
    vendor/semc/shakira/proprietary/lib/libvdmfumo.so:system/lib/libvdmfumo.so \
    vendor/semc/shakira/proprietary/lib/libfacedetectjnitest.so:system/lib/libfacedetectjnitest.so \
    vendor/semc/shakira/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/semc/shakira/proprietary/lib/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/semc/shakira/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/semc/shakira/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/semc/shakira/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/semc/shakira/proprietary/lib/libOmxQcelpDec.so:system/lib/libOmxQcelpDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/semc/shakira/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/semc/shakira/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/semc/shakira/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/semc/shakira/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/semc/shakira/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/semc/shakira/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/semc/shakira/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/semc/shakira/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so
