# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/mimmi/extract-files.sh

PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/akmd2:system/bin/akmd2 \
    vendor/semc/mimmi/proprietary/mm-venc-omx-test:system/bin/mm-venc-omx-test \
    vendor/semc/mimmi/proprietary/hciattach:system/bin/hciattach \
    vendor/semc/mimmi/proprietary/nvimport:system/bin/nvimport \
    vendor/semc/mimmi/proprietary/01_qcomm_omx.cfg:system/etc/01_qcomm_omx.cfg
    
## RIL related stuff 
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/libril.so:system/lib/libril.so \
    vendor/semc/mimmi/proprietary/port-bridge:system/bin/port-bridge \
    vendor/semc/mimmi/proprietary/qmuxd:system/bin/qmuxd \
    vendor/semc/mimmi/proprietary/libauth.so:system/lib/libauth.so \
    vendor/semc/mimmi/proprietary/libcm.so:system/lib/libcm.so \
    vendor/semc/mimmi/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/semc/mimmi/proprietary/libdll.so:system/lib/libdll.so \
    vendor/semc/mimmi/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/semc/mimmi/proprietary/libdss.so:system/lib/libdss.so \
    vendor/semc/mimmi/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/semc/mimmi/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/semc/mimmi/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/semc/mimmi/proprietary/libnv.so:system/lib/libnv.so \
    vendor/semc/mimmi/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/semc/mimmi/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/semc/mimmi/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/semc/mimmi/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/semc/mimmi/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/semc/mimmi/proprietary/libuim.so:system/lib/libuim.so \
    vendor/semc/mimmi/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/semc/mimmi/proprietary/libwms.so:system/lib/libwms.so \
    vendor/semc/mimmi/proprietary/libwmsts.so:system/lib/libwmsts.so
    
## Firmware
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/semc/mimmi/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/semc/mimmi/proprietary/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/mimmi/proprietary/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/mimmi/proprietary/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/mimmi/proprietary/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/mimmi/proprietary/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/mimmi/proprietary/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/mimmi/proprietary/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts  \
    vendor/semc/mimmi/proprietary/cy8_truetouch_tpk.hex:/system/etc/firmware/cy8_truetouch_tpk.hex \
    vendor/semc/mimmi/proprietary/cy8_truetouch_jtouch.hex:/system/etc/firmware/cy8_truetouch_jtouch.hex \
    vendor/semc/mimmi/proprietary/ts_fw_update.sh:/system/etc/ts_fw_update.sh

## Offline charging
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/chargemon:system/bin/charger \
    vendor/semc/mimmi/proprietary/libmiscta.so:system/lib/libmiscta.so \
    vendor/semc/mimmi/proprietary/semc_chargalg:system/bin/semc_chargalg \
    vendor/semc/mimmi/proprietary/updatemiscta:system/bin/updatemiscta \
    vendor/semc/mimmi/proprietary/anim1.rle:system/etc/semc/chargemon/anim1.rle \
    vendor/semc/mimmi/proprietary/anim2.rle:system/etc/semc/chargemon/anim2.rle \
    vendor/semc/mimmi/proprietary/anim3.rle:system/etc/semc/chargemon/anim3.rle \
    vendor/semc/mimmi/proprietary/anim4.rle:system/etc/semc/chargemon/anim4.rle \
    vendor/semc/mimmi/proprietary/anim5.rle:system/etc/semc/chargemon/anim5.rle \
    vendor/semc/mimmi/proprietary/anim6.rle:system/etc/semc/chargemon/anim6.rle \
    vendor/semc/mimmi/proprietary/anim7.rle:system/etc/semc/chargemon/anim7.rle \
    vendor/semc/mimmi/proprietary/anim8.rle:system/etc/semc/chargemon/anim8.rle
      
## FM Radio and ANT
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/com.sonyericsson.smfmf.xml:system/etc/permissions/com.sonyericsson.smfmf.xml \
    vendor/semc/mimmi/proprietary/com.sonyericsson.suquashi.xml:system/etc/permissions/com.sonyericsson.suquashi.xml \
    vendor/semc/mimmi/proprietary/com.ti.fm.fmreceiverif.xml:system/etc/permissions/com.ti.fm.fmreceiverif.xml \
    vendor/semc/mimmi/proprietary/libfm_stack.so:system/lib/libfm_stack.so \
    vendor/semc/mimmi/proprietary/libfmrx.so:system/lib/libfmrx.so \
    device/semc/mimmi/prebuilt/AntHalService.apk:system/app/AntHalService.apk \
    vendor/semc/mimmi/proprietary/com.dsi.ant.antradio_library.xml:system/etc/permissions/com.dsi.ant.antradio_library.xml \
    vendor/semc/mimmi/proprietary/com.dsi.ant.antradio_library.jar:system/framework/com.dsi.ant.antradio_library.jar \
    vendor/semc/mimmi/proprietary/libanthal.so:system/lib/libanthal.so

  
## HW and sensors
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/sensors.conf:system/etc/sensors.conf \
    vendor/semc/mimmi/proprietary/lights.default.so:system/lib/hw/lights.default.so \
    vendor/semc/mimmi/proprietary/gralloc.msm7k.so:system/lib/hw/gralloc.msm7k.so \
    vendor/semc/mimmi/proprietary/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/semc/mimmi/proprietary/copybit.msm7k.so:system/lib/hw/copybit.msm7k.so \
    vendor/semc/mimmi/proprietary/hal_seport.default.so:system/lib/hw/hal_seport.default.so \
    vendor/semc/mimmi/proprietary/libuinputdevicejni.so:system/lib/libsystemconnector/libuinputdevicejni.so \
    vendor/semc/mimmi/proprietary/libsystemconnector_hal_jni.so:system/lib/libsystemconnector_hal_jni.so

## Adreno 200 files
PRODUCT_COPY_FILES += \
    device/semc/mimmi/prebuilt/libgsl.so:system/lib/libgsl.so \
    device/semc/mimmi/prebuilt/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    device/semc/mimmi/prebuilt/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    device/semc/mimmi/prebuilt/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    device/semc/mimmi/prebuilt/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so
    
## Camera    
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/semc/mimmi/proprietary/libcamera.so:system/lib/libcamera.so \
    vendor/semc/mimmi/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/semc/mimmi/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/semc/mimmi/proprietary/libfacedetect.so:system/lib/libfacedetect.so \
    vendor/semc/mimmi/proprietary/libvdmfumo.so:system/lib/libvdmfumo.so \
    vendor/semc/mimmi/proprietary/libfacedetectjnitest.so:system/lib/libfacedetectjnitest.so \
    vendor/semc/mimmi/proprietary/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/semc/mimmi/proprietary/libopencore_common.so:system/lib/libopencore_common.so

## Audio
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/AudioFilterPlatform.csv:system/etc/AudioFilterPlatform.csv \
    vendor/semc/mimmi/proprietary/AudioFilterProduct.csv:system/etc/AudioFilterProduct.csv \
    vendor/semc/mimmi/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/semc/mimmi/proprietary/libaudio.so:system/lib/libaudio.so

## Hotspot
PRODUCT_COPY_FILES +=     device/semc/mimmi/prebuilt/tiap_loader.sh:system/bin/tiap_loader.sh \
    device/semc/mimmi/prebuilt/10dnsconf:system/etc/init.d/10dnsconf \
    device/semc/mimmi/prebuilt/10hostapconf:system/etc/init.d/10hostapconf \
    device/semc/mimmi/prebuilt/hostapd.conf:system/etc/wifi/softap/hostapd.conf \
    device/semc/mimmi/prebuilt/dnsmasq.conf:system/etc/wifi/dnsmasq.conf \
    device/semc/mimmi/prebuilt/tiwlan.ini:system/etc/wifi/tiwlan.ini \
    device/semc/mimmi/prebuilt/tiwlan_ap.ini:system/etc/wifi/softap/tiwlan_ap.ini \
    device/semc/mimmi/prebuilt/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin \
    device/semc/mimmi/prebuilt/tiwlan_firmware_ap.bin:system/etc/wifi/softap/tiwlan_firmware_ap.bin 

## OMX proprietaries
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/semc/mimmi/proprietary/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/semc/mimmi/proprietary/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/semc/mimmi/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/semc/mimmi/proprietary/libOmxQcelpDec.so:system/lib/libOmxQcelpDec.so \
    vendor/semc/mimmi/proprietary/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/semc/mimmi/proprietary/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/semc/mimmi/proprietary/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/semc/mimmi/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/semc/mimmi/proprietary/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/semc/mimmi/proprietary/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/semc/mimmi/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/semc/mimmi/proprietary/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/semc/mimmi/proprietary/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/semc/mimmi/proprietary/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/semc/mimmi/proprietary/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/semc/mimmi/proprietary/libOmxWmvDec.so:system/lib/libOmxWmvDec.so

# TS and slider
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/inputattach:system/bin/inputattach \
    vendor/semc/mimmi/proprietary/slidercounter:system/bin/slidercounter

## Keyboard layouts and T9
PRODUCT_COPY_FILES += \
    vendor/semc/mimmi/proprietary/mimmi_keypad.kl:system/usr/keylayout/mimmi_keypad.kl \
    vendor/semc/mimmi/proprietary/libZiEngine.so:system/lib/libZiEngine.so \
    device/semc/mimmi/prebuilt/usr/keychars/mimmi_keypad.kcm.bin:system/usr/keychars/mimmi_keypad.kcm.bin \
    device/semc/mimmi/prebuilt/usr/keychars/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
    device/semc/mimmi/prebuilt/usr/keychars/systemconnector.kcm.bin:system/usr/keychars/systemconnector.kcm.bin \
    device/semc/mimmi/prebuilt/usr/zi/Basque/Zi8DatEUs.z8d:system/usr/zi/Basque/Zi8DatEUs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Danish/Zi8DatDAs.z8d:system/usr/zi/Danish/Zi8DatDAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Estonian/Zi8DatETs.z8d:system/usr/zi/Estonian/Zi8DatETs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/German/Zi8DatDEs.z8d:system/usr/zi/German/Zi8DatDEs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Czech/Zi8DatCSs.z8d:system/usr/zi/Czech/Zi8DatCSs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Dutch/Zi8DatNLs.z8d:system/usr/zi/Dutch/Zi8DatNLs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Greek/Zi8DatELs.z8d:system/usr/zi/Greek/Zi8DatELs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Malay/Zi8DatMSs.z8d:system/usr/zi/Malay/Zi8DatMSs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Catalan/Zi8DatCAs.z8d:system/usr/zi/Catalan/Zi8DatCAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Romanian/Zi8DatROs.z8d:system/usr/zi/Romanian/Zi8DatROs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Polish/Zi8DatPLs.z8d:system/usr/zi/Polish/Zi8DatPLs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/French_CA/Zi8DatFRCAs.z8d:system/usr/zi/French_CA/Zi8DatFRCAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/French_EU/Zi8DatFREUs.z8d:system/usr/zi/French_EU/Zi8DatFREUs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Slovak/Zi8DatSKs.z8d:system/usr/zi/Slovak/Zi8DatSKs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Lithuanian/Zi8DatLTs.z8d:system/usr/zi/Lithuanian/Zi8DatLTs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Italian/Zi8DatITs.z8d:system/usr/zi/Italian/Zi8DatITs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Ukrainian/Zi8DatUKs.z8d:system/usr/zi/Ukrainian/Zi8DatUKs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Hungarian/Zi8DatHUs.z8d:system/usr/zi/Hungarian/Zi8DatHUs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Spanish_EU/Zi8DatESEUs.z8d:system/usr/zi/Spanish_EU/Zi8DatESEUs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Spanish_SA/Zi8DatESSAs.z8d:system/usr/zi/Spanish_SA/Zi8DatESSAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Galician/Zi8DatGLs.z8d:system/usr/zi/Galician/Zi8DatGLs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Latvian/Zi8DatLVs.z8d:system/usr/zi/Latvian/Zi8DatLVs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Serbian/Zi8DatSRLAs.z8d:system/usr/zi/Serbian/Zi8DatSRLAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Slovenian/Zi8DatSLs.z8d:system/usr/zi/Slovenian/Zi8DatSLs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Croatian/Zi8DatHRs.z8d:system/usr/zi/Croatian/Zi8DatHRs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Indonesian/Zi8DatINs.z8d:system/usr/zi/Indonesian/Zi8DatINs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Russian/Zi8DatRU.z8d:system/usr/zi/Russian/Zi8DatRU.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Tagalog/Zi8DatTLs.z8d:system/usr/zi/Tagalog/Zi8DatTLs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Bulgarian/Zi8DatBGs.z8d:system/usr/zi/Bulgarian/Zi8DatBGs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Finnish/Zi8DatFIs.z8d:system/usr/zi/Finnish/Zi8DatFIs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Swedish/Zi8DatSVs.z8d:system/usr/zi/Swedish/Zi8DatSVs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Norwegian/Zi8DatNOs.z8d:system/usr/zi/Norwegian/Zi8DatNOs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/English_AM/Zi8DatENAMs.z8d:system/usr/zi/English_AM/Zi8DatENAMs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/English_UK/Zi8DatENUKs.z8d:system/usr/zi/English_UK/Zi8DatENUKs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Turkish/Zi8DatTRs.z8d:system/usr/zi/Turkish/Zi8DatTRs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Portuguese_BZ/Zi8DatPTBZs.z8d:system/usr/zi/Portuguese_BZ/Zi8DatPTBZs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Portuguese_EU/Zi8DatPTEUs.z8d:system/usr/zi/Portuguese_EU/Zi8DatPTEUs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Arabic/Zi8DatARs.z8d:system/usr/zi/Arabic/Zi8DatARs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Farsi/Zi8DatFAs.z8d:system/usr/zi/Farsi/Zi8DatFAs.z8d \
    device/semc/mimmi/prebuilt/usr/zi/Hebrew/Zi8DatIWs.z8d:system/usr/zi/Hebrew/Zi8DatIWs.z8d \
    device/semc/mimmi/prebuilt/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    device/semc/mimmi/prebuilt/usr/keylayout/7k_handset.kl:system/usr/keylayout/7k_handset.kl \
    device/semc/mimmi/prebuilt/usr/keylayout/systemconnector.kl:system/usr/keylayout/systemconnector.kl \
    device/semc/mimmi/prebuilt/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/kaz.xml:system/usr/keyboard-config/languages/kaz.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/deu.xml:system/usr/keyboard-config/languages/deu.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/fra_ca.xml:system/usr/keyboard-config/languages/fra_ca.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/por_br.xml:system/usr/keyboard-config/languages/por_br.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/lav.xml:system/usr/keyboard-config/languages/lav.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ron.xml:system/usr/keyboard-config/languages/ron.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/lit.xml:system/usr/keyboard-config/languages/lit.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ell.xml:system/usr/keyboard-config/languages/ell.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/eng.xml:system/usr/keyboard-config/languages/eng.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/rus.xml:system/usr/keyboard-config/languages/rus.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/eng_us.xml:system/usr/keyboard-config/languages/eng_us.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/slk.xml:system/usr/keyboard-config/languages/slk.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/numberDecimal.xml:system/usr/keyboard-config/languages/numberDecimal.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/slv.xml:system/usr/keyboard-config/languages/slv.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/spa.xml:system/usr/keyboard-config/languages/spa.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/spa_la.xml:system/usr/keyboard-config/languages/spa_la.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/est.xml:system/usr/keyboard-config/languages/est.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/sqi.xml:system/usr/keyboard-config/languages/sqi.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/fin.xml:system/usr/keyboard-config/languages/fin.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/tgl.xml:system/usr/keyboard-config/languages/tgl.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/srp.xml:system/usr/keyboard-config/languages/srp.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/eus.xml:system/usr/keyboard-config/languages/eus.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/sun.xml:system/usr/keyboard-config/languages/sun.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/numberNatural.xml:system/usr/keyboard-config/languages/numberNatural.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/swe.xml:system/usr/keyboard-config/languages/swe.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/fra.xml:system/usr/keyboard-config/languages/fra.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/msa.xml:system/usr/keyboard-config/languages/msa.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/glg.xml:system/usr/keyboard-config/languages/glg.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/nld.xml:system/usr/keyboard-config/languages/nld.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/tur.xml:system/usr/keyboard-config/languages/tur.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ukr.xml:system/usr/keyboard-config/languages/ukr.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/nor.xml:system/usr/keyboard-config/languages/nor.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/phone.xml:system/usr/keyboard-config/languages/phone.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/numberInteger.xml:system/usr/keyboard-config/languages/numberInteger.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/hrv.xml:system/usr/keyboard-config/languages/hrv.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/hun.xml:system/usr/keyboard-config/languages/hun.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/cat.xml:system/usr/keyboard-config/languages/cat.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/jav.xml:system/usr/keyboard-config/languages/jav.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ind.xml:system/usr/keyboard-config/languages/ind.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/bos.xml:system/usr/keyboard-config/languages/bos.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ces.xml:system/usr/keyboard-config/languages/ces.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/pol.xml:system/usr/keyboard-config/languages/pol.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/por.xml:system/usr/keyboard-config/languages/por.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ita.xml:system/usr/keyboard-config/languages/ita.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/isl.xml:system/usr/keyboard-config/languages/isl.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/bul.xml:system/usr/keyboard-config/languages/bul.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/ara.xml:system/usr/keyboard-config/languages/ara.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/fas.xml:system/usr/keyboard-config/languages/fas.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/heb.xml:system/usr/keyboard-config/languages/heb.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/languages/dan.xml:system/usr/keyboard-config/languages/dan.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/keyprint.xml:system/usr/keyboard-config/keyprint.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/arabic.xml:system/usr/keyboard-config/layouts/arabic.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/azerty.xml:system/usr/keyboard-config/layouts/azerty.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/cyrillic.xml:system/usr/keyboard-config/layouts/cyrillic.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/greek.xml:system/usr/keyboard-config/layouts/greek.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/hebrew.xml:system/usr/keyboard-config/layouts/hebrew.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-arabic-azerty.xml:system/usr/keyboard-config/layouts/latin-on-arabic-azerty.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-arabic.xml:system/usr/keyboard-config/layouts/latin-on-arabic.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-bopomofo.xml:system/usr/keyboard-config/layouts/latin-on-bopomofo.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-cyrillic.xml:system/usr/keyboard-config/layouts/latin-on-cyrillic.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-greek.xml:system/usr/keyboard-config/layouts/latin-on-greek.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-hebrew.xml:system/usr/keyboard-config/layouts/latin-on-hebrew.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-korean.xml:system/usr/keyboard-config/layouts/latin-on-korean.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-pinyin.xml:system/usr/keyboard-config/layouts/latin-on-pinyin.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/latin-on-thai.xml:system/usr/keyboard-config/layouts/latin-on-thai.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/qwerty-br.xml:system/usr/keyboard-config/layouts/qwerty-br.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/qwerty-en.xml:system/usr/keyboard-config/layouts/qwerty-en.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/qwerty-no-dk.xml:system/usr/keyboard-config/layouts/qwerty-no-dk.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/qwerty-se-fi.xml:system/usr/keyboard-config/layouts/qwerty-se-fi.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/layouts/qwertz.xml:system/usr/keyboard-config/layouts/qwertz.xml \
    device/semc/mimmi/prebuilt/usr/keyboard-config/keyprint_qwertz.xml:system/usr/keyboard-config/keyprint_qwertz.xml
                
